# This file was automatically generated by SWIG (https://www.swig.org).
# Version 4.4.1
#
# Do not make changes to this file unless you know what you are doing - modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
# Import the low-level C/C++ module
if getattr(globals().get("__spec__"), "parent", None) or __package__ or "." in __name__:
    from . import _amaiss
else:
    import _amaiss

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "this":
            set(self, name, value)
        elif name == "thisown":
            self.this.own(value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


U8 = _amaiss.U8
U16 = _amaiss.U16
U32 = _amaiss.U32
U64 = _amaiss.U64
class SparseVectorView(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    indices = property(_amaiss.SparseVectorView_indices_get, _amaiss.SparseVectorView_indices_set)
    values = property(_amaiss.SparseVectorView_values_get, _amaiss.SparseVectorView_values_set)

    def __init__(self):
        _amaiss.SparseVectorView_swiginit(self, _amaiss.new_SparseVectorView())
    __swig_destroy__ = _amaiss.delete_SparseVectorView

# Register SparseVectorView in _amaiss:
_amaiss.SparseVectorView_swigregister(SparseVectorView)
class SparseVectors(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, value_size):
        _amaiss.SparseVectors_swiginit(self, _amaiss.new_SparseVectors(value_size))

    def add(self, indptr, indices, weights):
        return _amaiss.SparseVectors_add(self, indptr, indices, weights)

    def get_vector(self, vector_idx):
        return _amaiss.SparseVectors_get_vector(self, vector_idx)

    def num_vectors(self):
        return _amaiss.SparseVectors_num_vectors(self)
    __swig_destroy__ = _amaiss.delete_SparseVectors

# Register SparseVectors in _amaiss:
_amaiss.SparseVectors_swigregister(SparseVectors)
class Index(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _amaiss.delete_Index

    def add(self, n, indptr, indices, values):
        return _amaiss.Index_add(self, n, indptr, indices, values)

    def search(self, n, indptr, indices, values, k):
        return _amaiss.Index_search(self, n, indptr, indices, values, k)

    def get_vectors(self):
        return _amaiss.Index_get_vectors(self)

# Register Index in _amaiss:
_amaiss.Index_swigregister(Index)
class BrutalIndex(Index):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _amaiss.BrutalIndex_swiginit(self, _amaiss.new_BrutalIndex())
    __swig_destroy__ = _amaiss.delete_BrutalIndex

# Register BrutalIndex in _amaiss:
_amaiss.BrutalIndex_swigregister(BrutalIndex)

